
CREATE TABLE IF NOT EXISTS `comandaDigital`.`TB06_Cliente` (
  `NU_CLIENTE` BINARY(16) NOT NULL,
  `CPF` VARCHAR(11) NOT NULL,
  `NOME` VARCHAR(45) NOT NULL,
  `TELEFONE` VARCHAR(11) NOT NULL,
  `EMAIL` VARCHAR(45) NOT NULL,
  `SENHA` TEXT(155) NOT NULL,
  `NU_PERFIL` INT NOT NULL,
  `NU_MESA` INT NULL,
  PRIMARY KEY (`NU_CLIENTE`),
  UNIQUE INDEX `cpf_UNIQUE` (`CPF` ASC) ,
  UNIQUE INDEX `email_UNIQUE` (`EMAIL` ASC) ,
  INDEX `fk_Cliente_Perfil1_idx` (`NU_PERFIL` ASC) ,
  INDEX `fk_TB06_Cliente_TB07_Mesa1_idx` (`NU_MESA` ASC) ,
  UNIQUE INDEX `TELEFONE_UNIQUE` (`TELEFONE` ASC) ,
  CONSTRAINT `fk_Cliente_Perfil1`
    FOREIGN KEY (`NU_PERFIL`)
    REFERENCES `comandaDigital`.`TB01_Perfil` (`NU_PERFIL`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_TB06_Cliente_TB07_Mesa1`
    FOREIGN KEY (`NU_MESA`)
    REFERENCES `comandaDigital`.`TB07_Mesa` (`NU_MESA`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;