CREATE TABLE IF NOT EXISTS `comandaDigital`.`TB02_Gerente` (
  `NU_GERENTE`  INT NOT NULL AUTO_INCREMENT,
  `MATRICULA` VARCHAR(10) NOT NULL,
  `NOME` VARCHAR(45) NOT NULL,
  `CPF` VARCHAR(11) NOT NULL,
  `SENHA` TEXT(155) NOT NULL,
  `TELEFONE` VARCHAR(11) NOT NULL,
  `EMAIL` VARCHAR(45) NOT NULL,
  `NU_PERFIL` INT NOT NULL,
  PRIMARY KEY (`NU_GERENTE`),
  UNIQUE INDEX `cpf_UNIQUE` (`CPF` ASC) ,
  UNIQUE INDEX `email_UNIQUE` (`EMAIL` ASC) ,
 UNIQUE INDEX `matricula_UNIQUE` (`MATRICULA` ASC) ,
  INDEX `fk_Gerente_Perfil1_idx` (`NU_PERFIL` ASC) ,
  CONSTRAINT `fk_Gerente_Perfil1`
    FOREIGN KEY (`NU_PERFIL`)
    REFERENCES `comandaDigital`.`TB01_Perfil` (`NU_PERFIL`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;
