CREATE TABLE IF NOT EXISTS `comandaDigital`.`TB14_FeedBack` (
  `NU_FEEDBACK` INT NOT NULL AUTO_INCREMENT,
  `AVALIACAO` INT NOT NULL,
  `COMENTARIO` VARCHAR(45) NULL,
  `NU_CLIENTE` BINARY(16) NOT NULL,
  `NU_ITEM` INT NOT NULL,
  PRIMARY KEY (`NU_FEEDBACK`),
  INDEX `fk_FeedBack_Cliente1_idx` (`NU_CLIENTE` ASC) ,
  INDEX `fk_FeedBack_Item1_idx` (`NU_ITEM` ASC) ,
  CONSTRAINT `fk_FeedBack_Cliente1`
    FOREIGN KEY (`NU_CLIENTE`)
    REFERENCES `comandaDigital`.`TB06_Cliente` (`NU_CLIENTE`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_FeedBack_Item1`
    FOREIGN KEY (`NU_ITEM`)
    REFERENCES `comandaDigital`.`TB11_Item` (`NU_ITEM`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;